# Generated by Django 3.1.7 on 2021-03-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('max_draft', models.FloatField()),
                ('capacity', models.FloatField()),
            ],
        ),
    ]
