# Generated by Django 3.1.7 on 2021-03-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('anc_area', models.FloatField()),
                ('berth_length', models.FloatField()),
                ('ww_length', models.FloatField()),
                ('slots_num', models.IntegerField()),
                ('cranes_num', models.IntegerField()),
                ('allowable_draft', models.FloatField()),
            ],
        ),
    ]
